### ISSUE TITLE
bug: Add Get Permission to kubebuilder:rbac:group:argoproj.io

### ISSUE THREAD

**Issue by benoitschipper** [belastingdienst/opr-paas#141]
# Bug Report

**PAAS Operator version:**

[v0.11.0](https://github.com/belastingdienst/opr-paas/releases/tag/v0.11.0)
Still valid for 0.12.0

**Current behavior:**

The Paas operator is not allowed to Get any argo related resource according to the kubebuilder markers. This results in not permitted to Get for example applicationsets in the specified applicationset_namespace namespace.

**Steps to reproduce:**

1. Deploy Paas version 0.11.0 
2. Create an Applicationset in the designated applicationset_namespace
3. Apply a Paas with argoCD Capability enabled
```
apiVersion: cpet.belastingdienst.nl/v1alpha1
kind: Paas
metadata:
  name: tst-tst
spec:
  capabilities:
    argocd:
      enabled: true
      gitPath: environments/production
      gitRevision: main
      gitUrl: 'ssh://git@git.example.nl/example/example-repo.git'
    grafana: {}
    sso: {}
    tekton: {}
  quota:
    limits.cpu: '40'
    limits.memory: 64Gi
    requests.cpu: '20'
    requests.memory: 32Gi
    requests.storage: 200Gi
  requestor: cake
  ```

Result:

- The Paas Operator Creates the namespace including the quota, the ArgoCD, the bootstrap application.
- The Paas Operator controller keeps reconciling the PaasNs Object.
- The ApplicationSet is not update with the expected entry within the list generator

After changing the ClusterRole `manager-role` to allow for patching `ApplicationSets`, the `ApplicationSet` is now patched with the expected entry within the list generator.

**Other information:**

I also find the ClusterRole `manager-role` to be too generic and I suggest to rename it to something like `paas-manager-role` to make it easier for people to find. But i will make a separate issue and PR for this.
