### ISSUE TITLE
bug: Using the same group name in different PaaS resources leads to a combined group of users

### ISSUE THREAD

**Issue by PatrickDerichs** [belastingdienst/opr-paas#289]
# Bug Report

**Paas Operator version:**

v1.2.0

**Current behaviour:**

When I use a group name in a PaaS object that already exists in another PaaS object, it will reuse the existing one and add the users to the existing group. This can lead to granting unwanted access to users who were in the created group object.

**Expected behaviour:**

I would either expect not to extend/change existing groups that were defined in other PaaS objects on the same cluster. It shouldn't affect each other or it should give an error if it tries to edit a group object from another PaaS object.

**Steps to reproduce:**

We have a paas1 and a paas2

```
kind: Paas
metadata:
  name: paas1
spec:
  groups:
    admin_group:
      users:
        - example_user1
```
```
kind: Paas
metadata:
  name: paas2
spec:
  groups:
    admin_group:
      users:
        - example_user2
```

Creating this will make it so that both example_user1 and example_user2 have admin rights in both PaaS objects and their related namespaces.

**Related code:**

N/A

**Other information:**

N/A
