### ISSUE TITLE
Groupname verification with RFC-1035 is too tight.

### ISSUE THREAD

**Issue by devotional-phoenix-97** [belastingdienst/opr-paas#408]
# Bug Report

**Paas Operator version:**

v1.5.0

**Current behaviour:**

When createign Paas, the groupnames variable is too thight.
In our case we have underscores in naming, but might also have uppercase letters, etc.

**Expected behaviour:**

Would be awesome if we could influence the groupnames verification.

**Steps to reproduce:**

create a paas like:
```
apiVersion: cpet.belastingdienst.nl/v1alpha1
kind: Paas
metadata:
  name: mypaas
spec:
  groups:
    my_group:
      users:
        - john
        - jane
  quota:
    limits.cpu: '1'
  requestor: me
```

And you receive an error like:
> Error "Invalid value: "my_group": a DNS-1035 label must consist of lower case alphanumeric characters or '-', start with an alphabetic character, and end with an alphanumeric character (e.g. 'my-name', or 'abc-123', regex used for validation is '[a-z]([-a-z0-9]*[a-z0-9])?')" for field "spec.groups".

**Related code:**

[code](https://github.com/belastingdienst/opr-paas/blob/v1.5.0/internal/webhook/v1alpha1/paas_webhook.go#L155-L161)

```
		for _, errString := range validation.IsDNS1035Label(name) {
			errs = append(errs, field.Invalid(
				field.NewPath("spec").Child("groups"),
				name,
				errString,
			))
		}
```

**Other information:**

I will issue a PR
