### ISSUE TITLE
feat: Merge RB entries

### ISSUE THREAD

**Issue by portly-halicore-76** [belastingdienst/opr-paas#595]
# Feature Request

**Describe the Feature Request**

It is possible that multiple equal entries end up in a rolebinding. This happens when there are multiple groups defined in a Paas with the same query value but a different groupKey. This is functionally unusually, but we must be able to deal with this.

Example paas groups entry:

```  
....  
  groups:
    - test_test:
         query: CN=tester
    - test_test2:
         query: CN=tester
```

Resulting in the following rolebinding entry:

```
.....
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: tester
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: tester
```

**Describe Preferred Solution**

Merge the same entries in a rolebinding to one entry.

**Describe Alternatives**

X

**Related Code**

Assumable be here somewhere:

https://github.com/belastingdienst/opr-paas/blob/main/internal/controller/rolebindings_controller.go#L188-L199

**If the feature request is approved, would you be willing to submit a PR?**
_(Help can be provided if you need assistance submitting a PR)_

- [x] Yes
- [ ] No
